config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homes#index"
  get "home/about" => "homes#about"
  resources :users 
  resources :books do
  resource :favorites, only: [:create, :destroy]
  resources :post_comments, only: [:create, :destroy]
  
end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, :body, {presence: true}
  validates :body, length: { maximum: 200 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :comment, {presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image

 validates :name, length: {in: 2..20}
 validates :name, {presence: true}
 validates :introduction, length: { maximum: 50 }

  #登録時にメールアドレスを不要とする


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    #strong parametersを設定し、usernameを許可
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation] )


    #devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :password) }
  end


  def after_sign_in_path_for(resource)
      user_path(resource)
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!

  def new
    @book = Book.new
    @books = Book.all

  end

  def create
    @book = Book.new(book_image_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully"
      redirect_to  user_path(current_user.id)
    else
      @users = User.all
      @books = Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
     flash[:notice] = "ログインユーザーのものではありません"
     redirect_to books_path
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
     flash[:notice] = "ログインユーザーのものではありません"
     redirect_to books_path
    end
    if @book.update(book_image_params)
      flash[:notice] = "successfully"
     redirect_to book_path(@book)
    else
     render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def index
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @post_comment = PostComment.new
    
  end

  private
  def book_image_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
    
    def create
      @book = Book.find(params[:book_id])
      @favorite = Favorite.new
      @favorite.user_id = current_user.id
      @favorite.book_id = @book.id
      @favorite.save
      redirect_to request.referer#book_path(@book)
    end
    
    def destroy
      @book = Book.find(params[:book_id])
      @favorite = current_user.favorites.find_by(book_id: @book.id)
      @favorite.destroy
      redirect_to request.referer#book_path(@book)
    end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  

  def about
  end

  def index
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
    
    def create
      @book = Book.find(params[:book_id]) 
      @post_comment = PostComment.new(post_comment_params)
      @post_comment.user_id = current_user.id
      @post_comment.book_id = @book.id
      @post_comment.save
    
      redirect_to book_path(@book)
    end
    
    def show
      @book = Book.all
      
    end
    
    def destroy
      #binding.pry
      @book = Book.find(params[:book_id])
      @post_comment = PostComment.find_by(id: params[:id], book_id: params[:book_id])
      @post_comment.destroy
      redirect_to book_path(@book)
      
    end
    
    private
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @users = User.all
    @book = Book.new
  end


  def update
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:notice] = "ログインユーザーのものではありません"
      redirect_to user_path(current_user.id)
    end
    if @user.update(user_params)
      flash[:notice] ="successfully"
     redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:notice] = "ログインユーザーのものではありません"
      redirect_to user_path(current_user.id)
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/first_helper.rb
module FirstHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-xs-3">
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= book.errors.count %>errors prohibited this obj from being saved:</h2>
      <% book.errors.full_messages.each do |msg| %>
        <h3><%= msg %></h3>
      <% end %>
    </div>
  <% end %>

  <h2>User info</h2>


   <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", format: 'jpeg', size: "100x100"  %>
<table class="table table-striped">
  <tbody>
    <tr>

    <th>name</th>
    <th><%= user.name %></th>

    </tr>
  </tbody>

  <tbody>
    <tr>
  <th>introduction</th>
  <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>


   <%= link_to edit_user_path(user.id) do %>
          <i class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_6144" >
    </i>
      <% end %>


  <% if flash[:notice] %>
    <div class="flash">
        <%= flash[:notice] %>
        </div>
  <% end %>


     <div class="index-form">
       <%= form_with model:book, url: books_path(:user_id), method: :post, local: true do |f| %>

       <h2>New book</h2>

       <h4>Title</h4>
       <%= f.text_field :title %>

       <h4>Opinion</h4>
       <%= f.text_area :body %>

       <div class="actions row">
       <input type="submit" name="commit" value="Create Book" class="btn btn-primary col-xs-12" data-disable-with="Create Book">
       </div>
       <% end %>
     </div>
</div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
     <p>入力errorです</p>
    <div id="error_explanation">
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if flash[:notice] %>
    <div class="flash">
        <%= flash[:notice] %>
        </div>
  <% end %>


<div class="container">

        <p id="notice"></p>


      	<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>Editing Book</h1>
  <!-- <div class='col-md-3 col-md-offset-3'>
  </div> -->

	<%= form_with model:@book, local: true do |f| %>
  <div class="field row">
    <label for="book_title">Title</label>
  <%= f.text_field :title %>
  </div>

  <div class="field row">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body %>
  </div>

  <div class="actions row">
    <input type="submit" name="commit" value="Update Book" class="btn btn-primary col-xs-12" data-disable-with="Update Book">
  </div>
</form>
		<%= link_to "Show", book_path(@book.id) %>
		<%= link_to "Back", books_path %>
    </div>
    <div class="col-md-3"></div>
</div>
      </div>


<% end %>

app/views/books/index.html.erb
<div class="row">
  <%= render 'books/list', book: @book, user: current_user %>

  <div class="col-xs-9">
<h2>Books</h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user.id) do %>
            <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "30x30" %> <% end %></td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
                
                <td>
               <!-- ここから -->
<% if book.favorited_by?(current_user) %>
<li>
  <%= link_to book_favorites_path(book.id), method: :delete do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %> いいね
  <% end %>
</li>
<% else %>
<li>
  <%= link_to book_favorites_path(book.id), method: :post do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <%= book.favorites.count %> いいね
  <% end %>
</li>
<% end %>
<!-- ここまで -->
      </td>
      
      <td>
      <p class="comment-count">コメント数:<%= book.post_comments.count %></p>
      </td>
      
        </tr>
        <% end %>
      </tbody>
      

      
  　</table>
  </div>
</div>

app/views/books/new.html.erb
<%= render 'books/list', book: @book %>

<% @books.each do |book| %>

<h4>Title</h4>
<%= book.title %>

<h4>body</h4>
<%= book.body %>

<%= link_to "show", book_path(book.id) %>
<%= link_to "edit", edit_book_path(book.id) %>
<%= link_to "destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>

<% end %>

app/views/books/show.html.erb
<div class="row">

  <div class="col-xs-3">
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
      <% @book.errors.full_messages.each do |msg| %>
        <h3><%= msg %></h3>
      <% end %>
    </div>
  <% end %>

  <h2>User info</h2>


   <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
<table class="table table-striped">
  <tbody>
    <tr>

    <th>name</th>
    <th><%= @book.user.name %></th>

    </tr>
  </tbody>

  <tbody>
    <tr>
  <th>introduction</th>
  <th><%= @book.user.introduction %></th>
    </tr>
  </tbody>
</table>


   <%= link_to user_path(current_user) do %>
          <i class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_6144" >
    </i>
      <% end %>


  <% if flash[:notice] %>
    <div class="flash">
        <%= flash[:notice] %>
        </div>
  <% end %>


     <div class="index-form">
       <%= form_with model:@book_new, url: books_path, method: :post, local: true do |f| %>

       <h2>New book</h2>

       <h4>Title</h4>
       <%= f.text_field :title %>

       <h4>Opinion</h4>
       <%= f.text_area :body %>

       <div class="actions row">
       <%= f.submit "Create Book" %>
       </div>
       <% end %>
     </div>
</div>

  <div class="col-xs-9">

<h1>Book detail</h1>

<table class="table table-striped">

  <tr>
   <td><%= attachment_image_tag @book.user, :profile_image, fallback: "no_image.jpg", size: "100x100" %> <br>
<%= link_to @book.user.name, user_path(current_user) %></td>

   <td><%= link_to @book.title, book_path(@book.id) %></td>
   <td><%= @book.body %></td>
   <td>
     
     <td>
       <!-- ここから -->
<% if @book.favorited_by?(current_user) %>
<li>
  <%= link_to book_favorites_path(@book), method: :delete do %>
    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= @book.favorites.count %> いいね
  <% end %>
</li>
<% else %>
<li>
  <%= link_to book_favorites_path(@book), method: :post do %>
    <i class="fa fa-heart-o" aria-hidden="true"></i>
    <%= @book.favorites.count %> いいね
  <% end %>
</li>
<% end %>
<!-- ここまで -->
     </td>
     
  <td>   
    <% if user_signed_in? && current_user.id == @book.user_id %>
   <li>
     <span class="label label-success">
    <%= link_to "Edit", edit_book_path(@book) %>
    </span>
   <li>
     <span class="label label-danger">
    <%= link_to "Destroy", book_path(@book.id), method: :delete %>
    </span>
   </li>
   </td>
   
   
  <% end %>
   
  </tr>
  

  
  <td>
    <i class="fa fa-comment"></i>
    <%= link_to @book.post_comments.count %>
  </td>
  
 
  <td>
      <h2 class="comment-count"><%= @book.post_comments.count %>件コメント</h2>
  </td>
  
  </table>
  
<table>
  
  <tr>
  <% @book.post_comments.each do |post_comment| %>
  <td><%= attachment_image_tag post_comment.user, :profile_image, fallback: "no_image.jpg", size: "30x30" %>
  </td>
  <td><%= post_comment.comment %></td>
  <td>
      <% if post_comment.user.id == current_user.id %>
      <span class="label label-danger"><%= link_to "Destroy", book_post_comment_path(@book,post_comment), method: :delete %>
      </span>
      <% end %>
  </td>
  </tr> 
  
  <td><%= link_to @book.user.name, user_path(current_user) %></td>
   
  
       
  <% end %>
  
 
</table>
  
  <td>
  <!-- <form class="mt-20"> -->
<%= form_with(model:[@post_comment], url: book_post_comments_path(@book), local: true) do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
    </div>
  </div>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>
<!-- </form> -->
 
 </td>
 
 
  
  
  
  
  
  




  </div>
</div>

app/views/homes/about.html.erb
<div class="body">
      <div class="container">

        <p id="notice"></p>


      	<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>


      </div>
    </div>

app/views/homes/index.html.erb
<div class="body">
      <div class="container">

        <p id="notice"></p>


      	<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p><%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %></p>
      </div>
      <div class="row">
        <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
      </div>
    </div>

  </div>
</div>


      </div>
    </div>

    <footer>
  <div class="container">
  	<div class="row">
    	<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/fde22234ab.js" crossorigin="anonymous"></script>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container icon">
        <nav class="nav navbar-nav navbar-left">
          <span class="bookers">Bookers</span>
        </nav>
        <nav>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right ul-icon">
            <li>
              <span class="glyphicon glyphicon-home" aria-hidden="true">
                <%= link_to 'Home', user_path(current_user), class:"icon-home" %>
              </span>
            </li>
            <li>
              <span class="glyphicon glyphicon-user" aria-hidden="true">
                <%= link_to 'Users', users_path, class:"icon-home" %>
              </span>
            </li>
            <li>
              <span class="glyphicon glyphicon-book" aria-hidden="true">
                <%= link_to "Books", books_path, class:"icon-home" %>
              </span>
            </li>
            <li>
              <span class="glyphicon glyphicon-log-out" aria-hidden="true">
                <%= link_to "logout", destroy_user_session_path, method: :delete, class:"icon-home" %>
              </span>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right ul-icon">
            <li>
              <span class="glyphicon glyphicon-home" aria-hidden="true">
                <%= link_to "Home", root_path, class:"icon-home" %>
              </span>
            </li>
            <li>
              <span class="glyphicon glyphicon-link" aria-hidden="true">
                <%= link_to "About", home_about_path, class:"icon-home" %>
              </span>
            </li>
            <li>
              <span class="glyphicon glyphicon-edit" aria-hidden="true">
                <%= link_to "sign up", new_user_registration_path, class:"icon-home" %>
              </span>
            </li>
            <li>
              <span class="glyphicon glyphicon-log-in" aria-hidden="true">
                <%= link_to "login",  new_user_session_path, class:"icon-home" %>
              </span>
            </li>
          </ul>
        <% end %>
        </nav>
      </div>
    </nav>
  </header>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">

   <% if flash[:notice] %>
    <div class="flash">
        <%= flash[:notice] %>
        </div>
  <% end %>

 <%= yield %>
 </div>
  </body>
</html>

app/views/users/_list.html.erb
<div class="col-xs-3">
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= book.errors.count %>errors prohibited this obj from being saved:</h2>
      <% book.errors.full_messages.each do |msg| %>
        <h3><%= msg %></h3>
      <% end %>
    </div>
  <% end %>

  <h2>User info</h2>


   <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
<table class="table table-striped">
  <tbody>
    <tr>

    <th>name</th>
    <th><%= user.name %></th>

    </tr>
  </tbody>

  <tbody>
    <tr>
  <th>introduction</th>
  <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>


   <%= link_to edit_user_path(user.id) do %>
          <i class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_6144" >
    </i>
      <% end %>


  <% if flash[:notice] %>
    <div class="flash">
        <%= flash[:notice] %>
        </div>
  <% end %>


     <div class="index-form">
       <%= form_with model:@book, url: books_path, method: :post, local: true do |f| %>

       <h2>New book</h2>

       <h4>Title</h4>
       <%= f.text_field :title %>

       <h4>Opinion</h4>
       <%= f.text_area :body %>

       <div class="actions row">
       <input type="submit" name="commit" value="Create Book" class="btn btn-primary col-xs-12" data-disable-with="Create Book">
       </div>
       <% end %>
     </div>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
     <p>入力errorです</p>
    <div id="error_explanation">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if flash[:notice] %>
    <div class="flash">
        <%= flash[:notice] %>
        </div>
  <% end %>


<div class="container">

        <p id="notice"></p>


      	<h2>User info</h2>

<%= form_with model:@user, local:true do |f| %>


  <div class="field">
    <label for="user_name">Name</label>
    <%= f.text_field :name, autofocus: true %>

  </div>

  <div class="actions">
    <label for="user_image">image</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
  </div>

  <div class="field">
    <label for="user_introduction">introduction</label>
    <%= f.text_field :introduction , autofocus: true %>
  </div>


  <%= f.submit "Update User" %>

      </div>

      <% end %>

app/views/users/index.html.erb
<div class="row">
<%= render 'users/list', book: @book, user: current_user %>

  <div class="col-xs-9">
<h2>Users</h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "30x30" %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
        <% end %>
      </tbody>
  　</table>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
<%= render 'users/list', book: @book, current_user: @current_user, user: @user %>

  <div class="col-xs-9">
<h2>Books</h2>
    <table class="table table-striped">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "30x30" %></td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </tbody>
  　</table>
  </div>
</div>